# optional
name: first wf

on: push

jobs:
    first-job:
        # OS
        runs-on: ubuntu-latest
        # functions you'd like to run
        steps:
            - name: print my name
              run: echo "ITI"
